# Generated by Django 3.1.8 on 2021-05-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210508_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Link a tu cuenta de Facebook', null=True)),
                ('github', models.URLField(blank=True, help_text='Link a tu cuenta de GitHub', null=True)),
                ('gitlab', models.URLField(blank=True, help_text='Link a tu cuenta de GitLab', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Link a tu cuenta de Linkedin', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Link a tu cuenta de Instagram', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configuración de Redes Sociales',
            },
        ),
    ]
