# Generated by Django 3.1.8 on 2021-05-09 23:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_socialmediasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('studies', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Nombre de la Institución/Casa de Estudio.')), ('title', wagtail.core.blocks.CharBlock(help_text='Título Obtenido')), ('init_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que iniciaste.')), ('finished_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que culminaste.'))]))], blank=True, null=True),
        ),
    ]
