# Generated by Django 3.1.8 on 2021-05-10 02:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210510_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=wagtail.core.fields.StreamField([('studies', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock(help_text='Escribe el nombre del Icono. Ej. fa-node-js'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='studies',
            field=wagtail.core.fields.StreamField([('studies', wagtail.core.blocks.StructBlock([('institution', wagtail.core.blocks.CharBlock(help_text='Nombre de la Institución/Casa de Estudio.')), ('title', wagtail.core.blocks.CharBlock(help_text='Título Obtenido')), ('init_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que iniciaste.')), ('finished_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que culminaste.'))]))], blank=True, null=True),
        ),
    ]
