# Generated by Django 3.1.8 on 2021-05-11 16:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210511_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='experiences',
            field=wagtail.core.fields.StreamField([('experiences', wagtail.core.blocks.StructBlock([('position', wagtail.core.blocks.CharBlock(max_length=80)), ('enterprise', wagtail.core.blocks.CharBlock(max_length=200)), ('rol_description', wagtail.core.blocks.TextBlock(max_length=255)), ('init_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que iniciaste. Ej. Octubre 2012')), ('finished_date', wagtail.core.blocks.CharBlock(help_text='Mes y año en el que culminaste. Ej. Octubre 2018'))]))], blank=True, null=True),
        ),
    ]
