# Generated by Django 3.1.8 on 2021-05-11 17:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='interests',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Mis Intereses'),
        ),
    ]
