# Generated by Django 3.1.8 on 2021-05-11 18:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='awards',
            field=wagtail.core.fields.StreamField([('awards', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.CharBlock(max_length=255))]))], blank=True, null=True),
        ),
    ]
