# Generated by Django 3.1.8 on 2021-05-11 19:25

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_me',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Acerca de mi'),
        ),
    ]
