# Generated by Django 3.1.8 on 2021-05-11 19:44

from django.db import migrations
import portafolio.home.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210511_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_me',
            field=portafolio.home.fields.BoldAndItalicRichTextField(blank=True, null=True, verbose_name='Acerca de mi'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='interests',
            field=portafolio.home.fields.BoldAndItalicRichTextField(blank=True, null=True, verbose_name='Mis Intereses'),
        ),
    ]
